
begin_sys_respkg
    // text resource

    begin_text_res()
        text_res_gnumsg (R_LANG_zh_CN, R_ENCODING_utf8, "res/messages/zh_CN/LC_MESSAGES/helloworld.mo")
        text_res_gnumsg (R_LANG_zh_TW, R_ENCODING_utf8, "res/messages/zh_TW/LC_MESSAGES/helloworld.mo")
        text_res_gnumsg (R_LANG_en_US, R_ENCODING_utf8, "res/messages/en_US/LC_MESSAGES/helloworld.mo")
    end_text_res

end_sys_respkg

